// cd filename ,  cd ..- change directory (folder)

// Datatypes
// String
// Number
// Boolean
// undefined
// console.log()
// typeof()
// Varibles
// Var
// let
// const
// Scope
// block
// hoisting

// Conditional Statement
// 1. if else
// 2. switch

// Logical Operators
// && ||

// Function;
// Arrow function
// Traditional function

// var number=1;
// console.log(number);

// set of codes

// calculation
//  additon-> {code}
//  subtraction->{code}

//   cupboard-> function -> addition
//   cupboard->subtraction
//   cupboard->multiplication
//   cupboard->
//   cupboard->

//   variable-> to store Data
//   function-> to store multiple lines of code

//   Traditional function->

//   function sametime(){
//     console.log("Inside from function");
    
//  }
//  sametime();
//  console.log("Outside from function");

//   function addition(){
//     var number1=5;
//     var number2=5;
//     return number1+number2;
//     console.log("hiiii0");
    
//  }
//  const answer=addition();
//  console.log(answer, "answer");

// const number1=10;
// const number2=10;
// function Addition(){

//  return number1+number2;

// }
// function subtraction(){

//     return number1-number2;
    
//    }
//    console.log(subtraction(),Addition());

// const number1=10;
// const number2=10;

// function addition(first, second, third){
// return first+second;
// }

// function multiple(first, second, third){
//     return first*second;
//     }
//  function subtraction(first, second, third){
//         return first-second;
//         }

//  function diviton(first, second, third){
//             return first%second;
//             }
//             console.log(addition( number1,number2));
//             console.log(multiple( number1,number2));
//             console.log(subtraction( number1,number2)); 
//             console.log(diviton( number1,number2)); 
 
// function checkNumberIsEvenOrOdd(number){
//     if( number%2===0){
//         console.log("Even");
//     }else{
//         console.log("Odd");
//     }
// }
// checkNumberIsEvenOrOdd(25);


//Array
var students=["Rohit", "Nisha","Rohini","Vaishali"];
// console.log(students,"students");
// console.log(students.length);// start from 1,2,3...
// console.log(students[3]);//start from 0,1,2,3...
console.log()






